name: Build and Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  lint-tex:
    name: Lint TeX
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
      - name: 🚀 LaTeX linter
        uses: colinaaa/chktex-action@v1.1.2

  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build PDF and Upload
    needs: lint-tex
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3

      - name: 🤖 Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Twenty-Seconds_cv.tex
          post_compile: "mkdir build && mv Twenty-Seconds_cv.pdf build"

      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build
